//3270. Find the Key of the Numbers
/*
You are given three positive integers num1, num2, and num3.
The key of num1, num2, and num3 is defined as a four-digit number such that:
Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).
*/
class Solution {
public:
std::string zpad(std::string s,int n)
    {
        std::cout << s << ' ' << s.length() << '\n';
        
        //if(n >= s.length())
         //   return s;
        while(s.length() < n)
        {
            s.insert(s.begin(), '0');
        }
        //std::cout << s << '\n';
        return s;
    }
    
    int generateKey(int num1, int num2, int num3) {
       std::string s1{std::to_string(num1)};
	s1 = zpad(s1,4);
	std::string s2{std::to_string(num2)};
	s2 = zpad(s2,4);
	std::string s3{std::to_string(num3)};
	s3 = zpad(s3,4);
        //std::cout << s1 << ' ' << s2 << ' ' << s3 << '\n';
        std::string u{};
        for(int i = 0;i < 4;i++)
        {
            std::string t{std::min(std::min(s1[i],s2[i]),s3[i])};
            //std::cout << t << ' ';
            u = u + t;
        }

        return std::stoi(u);

    }

    
};
